### Get all objects
GET http://localhost:3000/api/boardgame

### Get object by id
GET http://localhost:3000/api/boardgame/1

### Post an object
POST http://localhost:3000/api/boardgame
Content-Type: application/json

{
  "id": "1",
  "name": "Nemesis",
  "description": "Escape the aliens",
  "published": 1993
}

### Update board game
PUT http://localhost:3000/api/boardgame/1
Content-Type: application/json

{
  "name": "Aureema",
  "description": "Escape the aliens",
  "published": 1999
}

### Delete all objects
DELETE http://localhost:3000/api/boardgame